In [1]:
user        = 'FA45088'
pwd         = 'your_pass'
factor2     = '01011995'
vc          = 'FA45088_U'
app_key     = '9005dfdhc2625256ab5612381d65b11'
imei        = 'ca57e1cb14411d1d558998'

In [2]:
from datetime import datetime, timedelta, date
import pandas as pd
import json

In [4]:
from NorenRestApiPy.NorenApi import  NorenApi


class ShoonyaApiPy(NorenApi):
    def __init__(self):
        NorenApi.__init__(self, host='https://shoonyatrade.finvasia.com/NorenWClientTP/', websocket='wss://shoonyatrade.finvasia.com/NorenWSTP/', eodhost='https://shoonya.finvasia.com/chartApi/getdata/')



#start of our program
api = ShoonyaApiPy()


 
#make the api call
ret = api.login(userid=user, password=pwd, twoFA=factor2, vendor_code=vc, api_secret=app_key, imei=imei)

ret['stat']

'Ok'

In [5]:
symbols = pd.read_csv('NIFTY50.csv')
symbolList = symbols['SYMBOL']
symbolList

0      COALINDIA
1     ASIANPAINT
2     BAJAJFINSV
3       RELIANCE
4           INFY
5            TCS
6            M&M
7     APOLLOHOSP
8       HDFCLIFE
9         MARUTI
10     BRITANNIA
11    ADANIPORTS
12          BPCL
13     KOTAKBANK
14    BAJFINANCE
15          HDFC
16       SBILIFE
17      DIVISLAB
18            LT
19    HINDUNILVR
20    INDUSINDBK
21         TITAN
22     SUNPHARMA
23          SBIN
24          NTPC
25      SHREECEM
26    HEROMOTOCO
27    TATAMOTORS
28     EICHERMOT
29         WIPRO
30        GRASIM
31       DRREDDY
32       HCLTECH
33           ITC
34    ULTRACEMCO
35         TECHM
36      HDFCBANK
37     NESTLEIND
38    BHARTIARTL
39     ICICIBANK
40    TATACONSUM
41      AXISBANK
42    BAJAJ-AUTO
43     POWERGRID
44           UPL
45      HINDALCO
46          ONGC
47      JSWSTEEL
48     TATASTEEL
49         CIPLA
Name: SYMBOL, dtype: object

In [7]:
symbolDf = pd.read_csv('https://shoonya.finvasia.com/NSE_symbols.txt.zip')
symbolDf

,Exchange,Token,LotSize,Symbol,TradingSymbol,Instrument,TickSize,Unnamed: 7
0,NSE,17635,1,ZYDUSWELL,ZYDUSWELL-EQ,EQ,0.05,NaN
1,NSE,7929,1,ZYDUSLIFE,ZYDUSLIFE-EQ,EQ,0.05,NaN
2,NSE,3827,1,ZUARIGLOB,ZUARIGLOB-EQ,EQ,0.05,NaN
3,NSE,29050,1,ZUARI,ZUARI-EQ,EQ,0.05,NaN
4,NSE,11394,1,ZOTA,ZOTA-EQ,EQ,0.05,NaN
...,...,...,...,...,...,...,...,...
4896,NSE,8018,100,182D040822,182D040822-TB,TB,0.01,NaN
4897,NSE,9327,100,182D031122,182D031122-TB,TB,0.01,NaN
4898,NSE,6996,100,182D020622,182D020622-TB,TB,0.01,NaN
4899,NSE,8339,100,182D010922,182D010922-TB,TB,0.01,NaN
4900,NSE,6833,1,1018GS2026,1018GS2026-GS,GS,0.01,NaN

In [9]:
filterSymbols = symbolDf[symbolDf.Symbol.isin(symbolList) & (symbolDf.Instrument =='EQ')]
filterSymbols

,Exchange,Token,LotSize,Symbol,TradingSymbol,Instrument,TickSize,Unnamed: 7
27,NSE,3787,1,WIPRO,WIPRO-EQ,EQ,0.05,NaN
238,NSE,11287,1,UPL,UPL-EQ,EQ,0.05,NaN
253,NSE,11532,1,ULTRACEMCO,ULTRACEMCO-EQ,EQ,0.05,NaN
319,NSE,3506,1,TITAN,TITAN-EQ,EQ,0.05,NaN
354,NSE,13538,1,TECHM,TECHM-EQ,EQ,0.05,NaN
359,NSE,11536,1,TCS,TCS-EQ,EQ,0.05,NaN
381,NSE,3499,1,TATASTEEL,TATASTEEL-EQ,EQ,0.05,NaN
384,NSE,3456,1,TATAMOTORS,TATAMOTORS-EQ,EQ,0.05,NaN
388,NSE,3432,1,TATACONSUM,TATACONSUM-EQ,EQ,0.05,NaN
445,NSE,3351,1,SUNPHARMA,SUNPHARMA-EQ,EQ,0.05,NaN
613,NSE,3103,1,SHREECEM,SHREECEM-EQ,EQ,0.05,NaN
836,NSE,3045,1,SBIN,SBIN-EQ,EQ,0.05,NaN
837,NSE,21808,1,SBILIFE,SBILIFE-EQ,EQ,0.05,NaN
946,NSE,2885,1,RELIANCE,RELIANCE-EQ,EQ,0.05,NaN
1047,NSE,14977,1,POWERGRID,POWERGRID-EQ,EQ,0.05,NaN
1176,NSE,2475,1,ONGC,ONGC-EQ,EQ,0.05,NaN
1210,NSE,11630,1,NTPC,NTPC-EQ,EQ,0.05,NaN
1298,NSE,17963,1,NESTLEIND,NESTLEIND-EQ,EQ,0.05,NaN
1449,NSE,10999,1,MARUTI,MARUTI-EQ,EQ,0.05,NaN
1518,NSE,2031,1,M&M,M&M-EQ,EQ,0.05,NaN
1532,NSE,11483,1,LT,LT-EQ,EQ,0.05,NaN
1634,NSE,1922,1,KOTAKBANK,KOTAKBANK-EQ,EQ,0.05,NaN
1704,NSE,11723,1,JSWSTEEL,JSWSTEEL-EQ,EQ,0.05,NaN
1770,NSE,1660,1,ITC,ITC-EQ,EQ,0.05,NaN
1833,NSE,1594,1,INFY,INFY-EQ,EQ,0.05,NaN
1840,NSE,5258,1,INDUSINDBK,INDUSINDBK-EQ,EQ,0.05,NaN
1981,NSE,4963,1,ICICIBANK,ICICIBANK-EQ,EQ,0.05,NaN
2109,NSE,1394,1,HINDUNILVR,HINDUNILVR-EQ,EQ,0.05,NaN
2117,NSE,1363,1,HINDALCO,HINDALCO-EQ,EQ,0.05,NaN
2127,NSE,1348,1,HEROMOTOCO,HEROMOTOCO-EQ,EQ,0.05,NaN
2140,NSE,467,1,HDFCLIFE,HDFCLIFE-EQ,EQ,0.05,NaN
2141,NSE,1333,1,HDFCBANK,HDFCBANK-EQ,EQ,0.05,NaN
2144,NSE,1330,1,HDFC,HDFC-EQ,EQ,0.05,NaN
2146,NSE,7229,1,HCLTECH,HCLTECH-EQ,EQ,0.05,NaN
2367,NSE,1232,1,GRASIM,GRASIM-EQ,EQ,0.05,NaN
2593,NSE,910,1,EICHERMOT,EICHERMOT-EQ,EQ,0.05,NaN
2660,NSE,881,1,DRREDDY,DRREDDY-EQ,EQ,0.05,NaN
2677,NSE,10940,1,DIVISLAB,DIVISLAB-EQ,EQ,0.05,NaN
2787,NSE,20374,1,COALINDIA,COALINDIA-EQ,EQ,0.05,NaN
2795,NSE,694,1,CIPLA,CIPLA-EQ,EQ,0.05,NaN
2865,NSE,547,1,BRITANNIA,BRITANNIA-EQ,EQ,0.05,NaN
2899,NSE,526,1,BPCL,BPCL-EQ,EQ,0.05,NaN
2926,NSE,10604,1,BHARTIARTL,BHARTIARTL-EQ,EQ,0.05,NaN
2987,NSE,317,1,BAJFINANCE,BAJFINANCE-EQ,EQ,0.05,NaN
2991,NSE,16675,1,BAJAJFINSV,BAJAJFINSV-EQ,EQ,0.05,NaN
2994,NSE,16669,1,BAJAJ-AUTO,BAJAJ-AUTO-EQ,EQ,0.05,NaN
3006,NSE,5900,1,AXISBANK,AXISBANK-EQ,EQ,0.05,NaN
3038,NSE,236,1,ASIANPAINT,ASIANPAINT-EQ,EQ,0.05,NaN
3073,NSE,157,1,APOLLOHOSP,APOLLOHOSP-EQ,EQ,0.05,NaN
3156,NSE,15083,1,ADANIPORTS,ADANIPORTS-EQ,EQ,0.05,NaN

In [10]:
start_date = datetime.today() - timedelta(days=10)
dayList = api.get_daily_price_series( 'NSE', 'ACC-EQ', startdate=start_date.timestamp(), enddate=None)
dayList

['{"time":"06-MAY-2022", "into":"2249.00", "inth":"2274.90", "intl":"2232.35", "intc":"2245.45", "ssboe":"1651795200", "intv":"571407.00"}',
 '{"time":"05-MAY-2022", "into":"2325.00", "inth":"2332.20", "intl":"2269.85", "intc":"2277.85", "ssboe":"1651708800", "intv":"395262.00"}',
 '{"time":"04-MAY-2022", "into":"2350.00", "inth":"2363.35", "intl":"2273.50", "intc":"2300.10", "ssboe":"1651622400", "intv":"451428.00"}',
 '{"time":"02-MAY-2022", "into":"2314.00", "inth":"2358.30", "intl":"2309.70", "intc":"2347.20", "ssboe":"1651449600", "intv":"490846.00"}']

In [11]:
def getprvDayCandle(symbol):
    try:
        start_date = datetime.today() - timedelta(days=10)
        dayList = api.get_daily_price_series( 'NSE', symbol, startdate=start_date.timestamp(), enddate=None)
        newDayList= []
        for i in dayList:
            newDayList.append(json.loads(i))
        dayDf = pd.DataFrame(newDayList)
        dayDf['time'] = pd.to_datetime(dayDf['time']).apply(lambda x: x.date())   
        dayDf.sort_values(by = 'time',inplace=True)
        if  dayDf.iloc[-1].time == datetime.now().date():
            return dayDf.iloc[-2].to_dict()
        else:
            return dayDf.iloc[-1].to_dict()  
    except Exception as e:
        print(symbol, e)

In [13]:
getprvDayCandle('ITC-EQ')

{'time': datetime.date(2022, 5, 6),
 'into': '259.00',
 'inth': '267.35',
 'intl': '258.90',
 'intc': '266.65',
 'ssboe': '1651795200',
 'intv': '34490123.00'}

In [14]:
symbolCloseList = []
for i in filterSymbols.index:
    symbolRow = filterSymbols.loc[i]
    cnadleInfo = getprvDayCandle(symbolRow.TradingSymbol)
    cnadleInfo.update({'symbol' : symbolRow.Symbol ,'token' : symbolRow.Token  })
    symbolCloseList.append(cnadleInfo)
    
symbolCloseList

[{'time': datetime.date(2022, 5, 6),
  'into': '490.00',
  'inth': '490.90',
  'intl': '481.00',
  'intc': '485.10',
  'ssboe': '1651795200',
  'intv': '9220891.00',
  'symbol': 'WIPRO',
  'token': 3787},
 {'time': datetime.date(2022, 5, 6),
  'into': '815.00',
  'inth': '815.00',
  'intl': '779.45',
  'intc': '786.85',
  'ssboe': '1651795200',
  'intv': '3256336.00',
  'symbol': 'UPL',
  'token': 11287},
 {'time': datetime.date(2022, 5, 6),
  'into': '6300.00',
  'inth': '6300.00',
  'intl': '6160.00',
  'intc': '6200.20',
  'ssboe': '1651795200',
  'intv': '499910.00',
  'symbol': 'ULTRACEMCO',
  'token': 11532},
 {'time': datetime.date(2022, 5, 6),
  'into': '2240.00',
  'inth': '2240.00',
  'intl': '2195.45',
  'intc': '2208.75',
  'ssboe': '1651795200',
  'intv': '1465638.00',
  'symbol': 'TITAN',
  'token': 3506},
 {'time': datetime.date(2022, 5, 6),
  'into': '1239.70',
  'inth': '1299.00',
  'intl': '1228.70',
  'intc': '1290.75',
  'ssboe': '1651795200',
  'intv': '5745203.00',
  'symbol': 'TECHM',
  'token': 13538},
 {'time': datetime.date(2022, 5, 6),
  'into': '3459.00',
  'inth': '3474.50',
  'intl': '3424.50',
  'intc': '3432.60',
  'ssboe': '1651795200',
  'intv': '2010812.00',
  'symbol': 'TCS',
  'token': 11536},
 {'time': datetime.date(2022, 5, 6),
  'into': '1268.00',
  'inth': '1290.00',
  'intl': '1243.00',
  'intc': '1283.70',
  'ssboe': '1651795200',
  'intv': '6925676.00',
  'symbol': 'TATASTEEL',
  'token': 3499},
 {'time': datetime.date(2022, 5, 6),
  'into': '418.85',
  'inth': '420.20',
  'intl': '407.00',
  'intc': '408.55',
  'ssboe': '1651795200',
  'intv': '25142225.00',
  'symbol': 'TATAMOTORS',
  'token': 3456},
 {'time': datetime.date(2022, 5, 6),
  'into': '770.00',
  'inth': '778.50',
  'intl': '762.95',
  'intc': '764.95',
  'ssboe': '1651795200',
  'intv': '2003395.00',
  'symbol': 'TATACONSUM',
  'token': 3432},
 {'time': datetime.date(2022, 5, 6),
  'into': '862.00',
  'inth': '885.70',
  'intl': '861.50',
  'intc': '883.30',
  'ssboe': '1651795200',
  'intv': '2350532.00',
  'symbol': 'SUNPHARMA',
  'token': 3351},
 {'time': datetime.date(2022, 5, 6),
  'into': '24850.00',
  'inth': '25059.20',
  'intl': '23850.00',
  'intc': '23973.65',
  'ssboe': '1651795200',
  'intv': '43939.00',
  'symbol': 'SHREECEM',
  'token': 3103},
 {'time': datetime.date(2022, 5, 6),
  'into': '471.00',
  'inth': '486.10',
  'intl': '471.00',
  'intc': '483.95',
  'ssboe': '1651795200',
  'intv': '16710020.00',
  'symbol': 'SBIN',
  'token': 3045},
 {'time': datetime.date(2022, 5, 6),
  'into': '1073.00',
  'inth': '1081.00',
  'intl': '1052.20',
  'intc': '1059.15',
  'ssboe': '1651795200',
  'intv': '1350057.00',
  'symbol': 'SBILIFE',
  'token': 21808},
 {'time': datetime.date(2022, 5, 6),
  'into': '2612.20',
  'inth': '2659.00',
  'intl': '2593.55',
  'intc': '2620.65',
  'ssboe': '1651795200',
  'intv': '9068448.00',
  'symbol': 'RELIANCE',
  'token': 2885},
 {'time': datetime.date(2022, 5, 6),
  'into': '231.45',
  'inth': '239.15',
  'intl': '231.45',
  'intc': '238.40',
  'ssboe': '1651795200',
  'intv': '13286390.00',
  'symbol': 'POWERGRID',
  'token': 14977},
 {'time': datetime.date(2022, 5, 6),
  'into': '163.90',
  'inth': '167.40',
  'intl': '161.10',
  'intc': '166.95',
  'ssboe': '1651795200',
  'intv': '16768573.00',
  'symbol': 'ONGC',
  'token': 2475},
 {'time': datetime.date(2022, 5, 6),
  'into': '156.45',
  'inth': '160.35',
  'intl': '156.05',
  'intc': '159.00',
  'ssboe': '1651795200',
  'intv': '22604305.00',
  'symbol': 'NTPC',
  'token': 11630},
 {'time': datetime.date(2022, 5, 6),
  'into': '17499.80',
  'inth': '17599.70',
  'intl': '16975.00',
  'intc': '16995.45',
  'ssboe': '1651795200',
  'intv': '89997.00',
  'symbol': 'NESTLEIND',
  'token': 17963},
 {'time': datetime.date(2022, 5, 6),
  'into': '7314.00',
  'inth': '7359.90',
  'intl': '7156.65',
  'intc': '7279.25',
  'ssboe': '1651795200',
  'intv': '650559.00',
  'symbol': 'MARUTI',
  'token': 10999},
 {'time': datetime.date(2022, 5, 6),
  'into': '890.00',
  'inth': '914.80',
  'intl': '887.30',
  'intc': '893.85',
  'ssboe': '1651795200',
  'intv': '4247088.00',
  'symbol': 'M&M',
  'token': 2031},
 {'time': datetime.date(2022, 5, 6),
  'into': '1616.00',
  'inth': '1633.00',
  'intl': '1612.10',
  'intc': '1622.45',
  'ssboe': '1651795200',
  'intv': '1439520.00',
  'symbol': 'LT',
  'token': 11483},
 {'time': datetime.date(2022, 5, 6),
  'into': '1755.15',
  'inth': '1794.95',
  'intl': '1750.00',
  'intc': '1775.30',
  'ssboe': '1651795200',
  'intv': '2847483.00',
  'symbol': 'KOTAKBANK',
  'token': 1922},
 {'time': datetime.date(2022, 5, 6),
  'into': '695.40',
  'inth': '700.90',
  'intl': '680.65',
  'intc': '690.40',
  'ssboe': '1651795200',
  'intv': '3930624.00',
  'symbol': 'JSWSTEEL',
  'token': 11723},
 {'time': datetime.date(2022, 5, 6),
  'into': '259.00',
  'inth': '267.35',
  'intl': '258.90',
  'intc': '266.65',
  'ssboe': '1651795200',
  'intv': '34490123.00',
  'symbol': 'ITC',
  'token': 1660},
 {'time': datetime.date(2022, 5, 6),
  'into': '1550.00',
  'inth': '1561.85',
  'intl': '1535.05',
  'intc': '1542.85',
  'ssboe': '1651795200',
  'intv': '6171472.00',
  'symbol': 'INFY',
  'token': 1594},
 {'time': datetime.date(2022, 5, 6),
  'into': '919.00',
  'inth': '934.30',
  'intl': '902.50',
  'intc': '915.40',
  'ssboe': '1651795200',
  'intv': '3713381.00',
  'symbol': 'INDUSINDBK',
  'token': 5258},
 {'time': datetime.date(2022, 5, 6),
  'into': '716.25',
  'inth': '723.00',
  'intl': '710.30',
  'intc': '719.25',
  'ssboe': '1651795200',
  'intv': '12455025.00',
  'symbol': 'ICICIBANK',
  'token': 4963},
 {'time': datetime.date(2022, 5, 6),
  'into': '2125.00',
  'inth': '2170.00',
  'intl': '2106.20',
  'intc': '2149.20',
  'ssboe': '1651795200',
  'intv': '1585602.00',
  'symbol': 'HINDUNILVR',
  'token': 1394},
 {'time': datetime.date(2022, 5, 6),
  'into': '450.00',
  'inth': '454.25',
  'intl': '439.00',
  'intc': '443.75',
  'ssboe': '1651795200',
  'intv': '8595262.00',
  'symbol': 'HINDALCO',
  'token': 1363},
 {'time': datetime.date(2022, 5, 6),
  'into': '2410.00',
  'inth': '2599.00',
  'intl': '2407.25',
  'intc': '2563.35',
  'ssboe': '1651795200',
  'intv': '2491483.00',
  'symbol': 'HEROMOTOCO',
  'token': 1348},
 {'time': datetime.date(2022, 5, 6),
  'into': '555.00',
  'inth': '573.75',
  'intl': '555.00',
  'intc': '565.95',
  'ssboe': '1651795200',
  'intv': '3969111.00',
  'symbol': 'HDFCLIFE',
  'token': 467},
 {'time': datetime.date(2022, 5, 6),
  'into': '1330.00',
  'inth': '1335.00',
  'intl': '1313.00',
  'intc': '1317.60',
  'ssboe': '1651795200',
  'intv': '13365634.00',
  'symbol': 'HDFCBANK',
  'token': 1333},
 {'time': datetime.date(2022, 5, 6),
  'into': '2170.00',
  'inth': '2190.00',
  'intl': '2142.75',
  'intc': '2150.65',
  'ssboe': '1651795200',
  'intv': '3862931.00',
  'symbol': 'HDFC',
  'token': 1330},
 {'time': datetime.date(2022, 5, 6),
  'into': '1049.90',
  'inth': '1056.65',
  'intl': '1028.95',
  'intc': '1050.20',
  'ssboe': '1651795200',
  'intv': '4075606.00',
  'symbol': 'HCLTECH',
  'token': 7229},
 {'time': datetime.date(2022, 5, 6),
  'into': '1590.40',
  'inth': '1604.40',
  'intl': '1551.05',
  'intc': '1565.60',
  'ssboe': '1651795200',
  'intv': '525582.00',
  'symbol': 'GRASIM',
  'token': 1232},
 {'time': datetime.date(2022, 5, 6),
  'into': '2410.00',
  'inth': '2418.20',
  'intl': '2351.35',
  'intc': '2362.45',
  'ssboe': '1651795200',
  'intv': '407390.00',
  'symbol': 'EICHERMOT',
  'token': 910},
 {'time': datetime.date(2022, 5, 6),
  'into': '3929.80',
  'inth': '3948.85',
  'intl': '3880.00',
  'intc': '3930.65',
  'ssboe': '1651795200',
  'intv': '239479.00',
  'symbol': 'DRREDDY',
  'token': 881},
 {'time': datetime.date(2022, 5, 6),
  'into': '4275.00',
  'inth': '4310.55',
  'intl': '4121.50',
  'intc': '4165.85',
  'ssboe': '1651795200',
  'intv': '684913.00',
  'symbol': 'DIVISLAB',
  'token': 10940},
 {'time': datetime.date(2022, 5, 6),
  'into': '184.50',
  'inth': '188.95',
  'intl': '183.05',
  'intc': '187.40',
  'ssboe': '1651795200',
  'intv': '14257553.00',
  'symbol': 'COALINDIA',
  'token': 20374},
 {'time': datetime.date(2022, 5, 6),
  'into': '937.80',
  'inth': '946.35',
  'intl': '925.40',
  'intc': '934.75',
  'ssboe': '1651795200',
  'intv': '1828238.00',
  'symbol': 'CIPLA',
  'token': 694},
 {'time': datetime.date(2022, 5, 6),
  'into': '3245.00',
  'inth': '3323.85',
  'intl': '3187.10',
  'intc': '3307.80',
  'ssboe': '1651795200',
  'intv': '560373.00',
  'symbol': 'BRITANNIA',
  'token': 547},
 {'time': datetime.date(2022, 5, 6),
  'into': '357.00',
  'inth': '359.80',
  'intl': '353.00',
  'intc': '357.30',
  'ssboe': '1651795200',
  'intv': '2348871.00',
  'symbol': 'BPCL',
  'token': 526},
 {'time': datetime.date(2022, 5, 6),
  'into': '711.25',
  'inth': '723.90',
  'intl': '707.75',
  'intc': '710.25',
  'ssboe': '1651795200',
  'intv': '5912312.00',
  'symbol': 'BHARTIARTL',
  'token': 10604},
 {'time': datetime.date(2022, 5, 6),
  'into': '6201.00',
  'inth': '6205.05',
  'intl': '5975.00',
  'intc': '6000.30',
  'ssboe': '1651795200',
  'intv': '3064865.00',
  'symbol': 'BAJFINANCE',
  'token': 317},
 {'time': datetime.date(2022, 5, 6),
  'into': '13800.00',
  'inth': '13895.30',
  'intl': '13510.00',
  'intc': '13640.50',
  'ssboe': '1651795200',
  'intv': '351616.00',
  'symbol': 'BAJAJFINSV',
  'token': 16675},
 {'time': datetime.date(2022, 5, 6),
  'into': '3488.30',
  'inth': '3555.00',
  'intl': '3460.00',
  'intc': '3499.75',
  'ssboe': '1651795200',
  'intv': '436366.00',
  'symbol': 'BAJAJ-AUTO',
  'token': 16669},
 {'time': datetime.date(2022, 5, 6),
  'into': '690.00',
  'inth': '692.50',
  'intl': '668.10',
  'intc': '673.40',
  'ssboe': '1651795200',
  'intv': '15511195.00',
  'symbol': 'AXISBANK',
  'token': 5900},
 {'time': datetime.date(2022, 5, 6),
  'into': '3020.00',
  'inth': '3052.40',
  'intl': '3003.90',
  'intc': '3016.25',
  'ssboe': '1651795200',
  'intv': '923941.00',
  'symbol': 'ASIANPAINT',
  'token': 236},
 {'time': datetime.date(2022, 5, 6),
  'into': '3898.65',
  'inth': '3898.65',
  'intl': '3791.05',
  'intc': '3827.35',
  'ssboe': '1651795200',
  'intv': '891448.00',
  'symbol': 'APOLLOHOSP',
  'token': 157},
 {'time': datetime.date(2022, 5, 6),
  'into': '797.90',
  'inth': '820.95',
  'intl': '790.20',
  'intc': '811.40',
  'ssboe': '1651795200',
  'intv': '6150326.00',
  'symbol': 'ADANIPORTS',
  'token': 15083}]

In [15]:
api.get_quotes(exchange='NSE', token='22')

{'request_time': '00:11:43 10-05-2022',
 'stat': 'Ok',
 'exch': 'NSE',
 'tsym': 'ACC-EQ',
 'cname': 'ACC LIMITED',
 'symname': 'ACC',
 'seg': 'EQT',
 'instname': 'EQ',
 'isin': 'INE012A01025',
 'pp': '2',
 'ls': '1',
 'ti': '0.05',
 'mult': '1',
 'lut': '1652091750',
 'uc': '2456.15',
 'lc': '2009.65',
 'toi': '3461500',
 'prcftr_d': '(1 / 1 ) * (1 / 1)',
 'token': '22',
 'lp': '2232.90',
 'c': '2245.45',
 'h': '2255.00',
 'l': '2201.50',
 'ap': '2223.84',
 'o': '2221.00',
 'v': '323573',
 'ltq': '92',
 'ltt': '15:52:30',
 'tbq': '0',
 'tsq': '487',
 'bp1': '0.00',
 'sp1': '2232.90',
 'bp2': '0.00',
 'sp2': '0.00',
 'bp3': '0.00',
 'sp3': '0.00',
 'bp4': '0.00',
 'sp4': '0.00',
 'bp5': '0.00',
 'sp5': '0.00',
 'bq1': '0',
 'sq1': '487',
 'bq2': '0',
 'sq2': '0',
 'bq3': '0',
 'sq3': '0',
 'bq4': '0',
 'sq4': '0',
 'bq5': '0',
 'sq5': '0',
 'bo1': '0',
 'so1': '4',
 'bo2': '0',
 'so2': '0',
 'bo3': '0',
 'so3': '0',
 'bo4': '0',
 'so4': '0',
 'bo5': '0',
 'so5': '0'}

In [16]:
symbolList = symbolCloseList.copy()
for i  in range(0,len(symbolList)):
    ltpres = api.get_quotes(exchange='NSE', token= str(symbolList[i]['token']))
    ltp = float(ltpres['lp'])
    symbolList[i].update({'ltp' :ltp})

In [17]:
symbolList

[{'time': datetime.date(2022, 5, 6),
  'into': '490.00',
  'inth': '490.90',
  'intl': '481.00',
  'intc': '485.10',
  'ssboe': '1651795200',
  'intv': '9220891.00',
  'symbol': 'WIPRO',
  'token': 3787,
  'ltp': 483.15},
 {'time': datetime.date(2022, 5, 6),
  'into': '815.00',
  'inth': '815.00',
  'intl': '779.45',
  'intc': '786.85',
  'ssboe': '1651795200',
  'intv': '3256336.00',
  'symbol': 'UPL',
  'token': 11287,
  'ltp': 777.6},
 {'time': datetime.date(2022, 5, 6),
  'into': '6300.00',
  'inth': '6300.00',
  'intl': '6160.00',
  'intc': '6200.20',
  'ssboe': '1651795200',
  'intv': '499910.00',
  'symbol': 'ULTRACEMCO',
  'token': 11532,
  'ltp': 6224.6},
 {'time': datetime.date(2022, 5, 6),
  'into': '2240.00',
  'inth': '2240.00',
  'intl': '2195.45',
  'intc': '2208.75',
  'ssboe': '1651795200',
  'intv': '1465638.00',
  'symbol': 'TITAN',
  'token': 3506,
  'ltp': 2183.2},
 {'time': datetime.date(2022, 5, 6),
  'into': '1239.70',
  'inth': '1299.00',
  'intl': '1228.70',
  'intc': '1290.75',
  'ssboe': '1651795200',
  'intv': '5745203.00',
  'symbol': 'TECHM',
  'token': 13538,
  'ltp': 1261.15},
 {'time': datetime.date(2022, 5, 6),
  'into': '3459.00',
  'inth': '3474.50',
  'intl': '3424.50',
  'intc': '3432.60',
  'ssboe': '1651795200',
  'intv': '2010812.00',
  'symbol': 'TCS',
  'token': 11536,
  'ltp': 3445.1},
 {'time': datetime.date(2022, 5, 6),
  'into': '1268.00',
  'inth': '1290.00',
  'intl': '1243.00',
  'intc': '1283.70',
  'ssboe': '1651795200',
  'intv': '6925676.00',
  'symbol': 'TATASTEEL',
  'token': 3499,
  'ltp': 1252.25},
 {'time': datetime.date(2022, 5, 6),
  'into': '418.85',
  'inth': '420.20',
  'intl': '407.00',
  'intc': '408.55',
  'ssboe': '1651795200',
  'intv': '25142225.00',
  'symbol': 'TATAMOTORS',
  'token': 3456,
  'ltp': 403.95},
 {'time': datetime.date(2022, 5, 6),
  'into': '770.00',
  'inth': '778.50',
  'intl': '762.95',
  'intc': '764.95',
  'ssboe': '1651795200',
  'intv': '2003395.00',
  'symbol': 'TATACONSUM',
  'token': 3432,
  'ltp': 758.25},
 {'time': datetime.date(2022, 5, 6),
  'into': '862.00',
  'inth': '885.70',
  'intl': '861.50',
  'intc': '883.30',
  'ssboe': '1651795200',
  'intv': '2350532.00',
  'symbol': 'SUNPHARMA',
  'token': 3351,
  'ltp': 885.4},
 {'time': datetime.date(2022, 5, 6),
  'into': '24850.00',
  'inth': '25059.20',
  'intl': '23850.00',
  'intc': '23973.65',
  'ssboe': '1651795200',
  'intv': '43939.00',
  'symbol': 'SHREECEM',
  'token': 3103,
  'ltp': 24058.3},
 {'time': datetime.date(2022, 5, 6),
  'into': '471.00',
  'inth': '486.10',
  'intl': '471.00',
  'intc': '483.95',
  'ssboe': '1651795200',
  'intv': '16710020.00',
  'symbol': 'SBIN',
  'token': 3045,
  'ltp': 475.9},
 {'time': datetime.date(2022, 5, 6),
  'into': '1073.00',
  'inth': '1081.00',
  'intl': '1052.20',
  'intc': '1059.15',
  'ssboe': '1651795200',
  'intv': '1350057.00',
  'symbol': 'SBILIFE',
  'token': 21808,
  'ltp': 1064.45},
 {'time': datetime.date(2022, 5, 6),
  'into': '2612.20',
  'inth': '2659.00',
  'intl': '2593.55',
  'intc': '2620.65',
  'ssboe': '1651795200',
  'intv': '9068448.00',
  'symbol': 'RELIANCE',
  'token': 2885,
  'ltp': 2518.3},
 {'time': datetime.date(2022, 5, 6),
  'into': '231.45',
  'inth': '239.15',
  'intl': '231.45',
  'intc': '238.40',
  'ssboe': '1651795200',
  'intv': '13286390.00',
  'symbol': 'POWERGRID',
  'token': 14977,
  'ltp': 245.15},
 {'time': datetime.date(2022, 5, 6),
  'into': '163.90',
  'inth': '167.40',
  'intl': '161.10',
  'intc': '166.95',
  'ssboe': '1651795200',
  'intv': '16768573.00',
  'symbol': 'ONGC',
  'token': 2475,
  'ltp': 164.75},
 {'time': datetime.date(2022, 5, 6),
  'into': '156.45',
  'inth': '160.35',
  'intl': '156.05',
  'intc': '159.00',
  'ssboe': '1651795200',
  'intv': '22604305.00',
  'symbol': 'NTPC',
  'token': 11630,
  'ltp': 159.0},
 {'time': datetime.date(2022, 5, 6),
  'into': '17499.80',
  'inth': '17599.70',
  'intl': '16975.00',
  'intc': '16995.45',
  'ssboe': '1651795200',
  'intv': '89997.00',
  'symbol': 'NESTLEIND',
  'token': 17963,
  'ltp': 16504.35},
 {'time': datetime.date(2022, 5, 6),
  'into': '7314.00',
  'inth': '7359.90',
  'intl': '7156.65',
  'intc': '7279.25',
  'ssboe': '1651795200',
  'intv': '650559.00',
  'symbol': 'MARUTI',
  'token': 10999,
  'ltp': 7360.3},
 {'time': datetime.date(2022, 5, 6),
  'into': '890.00',
  'inth': '914.80',
  'intl': '887.30',
  'intc': '893.85',
  'ssboe': '1651795200',
  'intv': '4247088.00',
  'symbol': 'M&M',
  'token': 2031,
  'ltp': 895.3},
 {'time': datetime.date(2022, 5, 6),
  'into': '1616.00',
  'inth': '1633.00',
  'intl': '1612.10',
  'intc': '1622.45',
  'ssboe': '1651795200',
  'intv': '1439520.00',
  'symbol': 'LT',
  'token': 11483,
  'ltp': 1616.15},
 {'time': datetime.date(2022, 5, 6),
  'into': '1755.15',
  'inth': '1794.95',
  'intl': '1750.00',
  'intc': '1775.30',
  'ssboe': '1651795200',
  'intv': '2847483.00',
  'symbol': 'KOTAKBANK',
  'token': 1922,
  'ltp': 1767.5},
 {'time': datetime.date(2022, 5, 6),
  'into': '695.40',
  'inth': '700.90',
  'intl': '680.65',
  'intc': '690.40',
  'ssboe': '1651795200',
  'intv': '3930624.00',
  'symbol': 'JSWSTEEL',
  'token': 11723,
  'ltp': 678.35},
 {'time': datetime.date(2022, 5, 6),
  'into': '259.00',
  'inth': '267.35',
  'intl': '258.90',
  'intc': '266.65',
  'ssboe': '1651795200',
  'intv': '34490123.00',
  'symbol': 'ITC',
  'token': 1660,
  'ltp': 262.95},
 {'time': datetime.date(2022, 5, 6),
  'into': '1550.00',
  'inth': '1561.85',
  'intl': '1535.05',
  'intc': '1542.85',
  'ssboe': '1651795200',
  'intv': '6171472.00',
  'symbol': 'INFY',
  'token': 1594,
  'ltp': 1570.35},
 {'time': datetime.date(2022, 5, 6),
  'into': '919.00',
  'inth': '934.30',
  'intl': '902.50',
  'intc': '915.40',
  'ssboe': '1651795200',
  'intv': '3713381.00',
  'symbol': 'INDUSINDBK',
  'token': 5258,
  'ltp': 889.7},
 {'time': datetime.date(2022, 5, 6),
  'into': '716.25',
  'inth': '723.00',
  'intl': '710.30',
  'intc': '719.25',
  'ssboe': '1651795200',
  'intv': '12455025.00',
  'symbol': 'ICICIBANK',
  'token': 4963,
  'ltp': 710.35},
 {'time': datetime.date(2022, 5, 6),
  'into': '2125.00',
  'inth': '2170.00',
  'intl': '2106.20',
  'intc': '2149.20',
  'ssboe': '1651795200',
  'intv': '1585602.00',
  'symbol': 'HINDUNILVR',
  'token': 1394,
  'ltp': 2116.65},
 {'time': datetime.date(2022, 5, 6),
  'into': '450.00',
  'inth': '454.25',
  'intl': '439.00',
  'intc': '443.75',
  'ssboe': '1651795200',
  'intv': '8595262.00',
  'symbol': 'HINDALCO',
  'token': 1363,
  'ltp': 444.1},
 {'time': datetime.date(2022, 5, 6),
  'into': '2410.00',
  'inth': '2599.00',
  'intl': '2407.25',
  'intc': '2563.35',
  'ssboe': '1651795200',
  'intv': '2491483.00',
  'symbol': 'HEROMOTOCO',
  'token': 1348,
  'ltp': 2492.75},
 {'time': datetime.date(2022, 5, 6),
  'into': '555.00',
  'inth': '573.75',
  'intl': '555.00',
  'intc': '565.95',
  'ssboe': '1651795200',
  'intv': '3969111.00',
  'symbol': 'HDFCLIFE',
  'token': 467,
  'ltp': 563.85},
 {'time': datetime.date(2022, 5, 6),
  'into': '1330.00',
  'inth': '1335.00',
  'intl': '1313.00',
  'intc': '1317.60',
  'ssboe': '1651795200',
  'intv': '13365634.00',
  'symbol': 'HDFCBANK',
  'token': 1333,
  'ltp': 1319.85},
 {'time': datetime.date(2022, 5, 6),
  'into': '2170.00',
  'inth': '2190.00',
  'intl': '2142.75',
  'intc': '2150.65',
  'ssboe': '1651795200',
  'intv': '3862931.00',
  'symbol': 'HDFC',
  'token': 1330,
  'ltp': 2168.3},
 {'time': datetime.date(2022, 5, 6),
  'into': '1049.90',
  'inth': '1056.65',
  'intl': '1028.95',
  'intc': '1050.20',
  'ssboe': '1651795200',
  'intv': '4075606.00',
  'symbol': 'HCLTECH',
  'token': 7229,
  'ltp': 1076.1},
 {'time': datetime.date(2022, 5, 6),
  'into': '1590.40',
  'inth': '1604.40',
  'intl': '1551.05',
  'intc': '1565.60',
  'ssboe': '1651795200',
  'intv': '525582.00',
  'symbol': 'GRASIM',
  'token': 1232,
  'ltp': 1551.75},
 {'time': datetime.date(2022, 5, 6),
  'into': '2410.00',
  'inth': '2418.20',
  'intl': '2351.35',
  'intc': '2362.45',
  'ssboe': '1651795200',
  'intv': '407390.00',
  'symbol': 'EICHERMOT',
  'token': 910,
  'ltp': 2344.3},
 {'time': datetime.date(2022, 5, 6),
  'into': '3929.80',
  'inth': '3948.85',
  'intl': '3880.00',
  'intc': '3930.65',
  'ssboe': '1651795200',
  'intv': '239479.00',
  'symbol': 'DRREDDY',
  'token': 881,
  'ltp': 3905.8},
 {'time': datetime.date(2022, 5, 6),
  'into': '4275.00',
  'inth': '4310.55',
  'intl': '4121.50',
  'intc': '4165.85',
  'ssboe': '1651795200',
  'intv': '684913.00',
  'symbol': 'DIVISLAB',
  'token': 10940,
  'ltp': 4231.1},
 {'time': datetime.date(2022, 5, 6),
  'into': '184.50',
  'inth': '188.95',
  'intl': '183.05',
  'intc': '187.40',
  'ssboe': '1651795200',
  'intv': '14257553.00',
  'symbol': 'COALINDIA',
  'token': 20374,
  'ltp': 183.05},
 {'time': datetime.date(2022, 5, 6),
  'into': '937.80',
  'inth': '946.35',
  'intl': '925.40',
  'intc': '934.75',
  'ssboe': '1651795200',
  'intv': '1828238.00',
  'symbol': 'CIPLA',
  'token': 694,
  'ltp': 938.3},
 {'time': datetime.date(2022, 5, 6),
  'into': '3245.00',
  'inth': '3323.85',
  'intl': '3187.10',
  'intc': '3307.80',
  'ssboe': '1651795200',
  'intv': '560373.00',
  'symbol': 'BRITANNIA',
  'token': 547,
  'ltp': 3252.05},
 {'time': datetime.date(2022, 5, 6),
  'into': '357.00',
  'inth': '359.80',
  'intl': '353.00',
  'intc': '357.30',
  'ssboe': '1651795200',
  'intv': '2348871.00',
  'symbol': 'BPCL',
  'token': 526,
  'ltp': 353.4},
 {'time': datetime.date(2022, 5, 6),
  'into': '711.25',
  'inth': '723.90',
  'intl': '707.75',
  'intc': '710.25',
  'ssboe': '1651795200',
  'intv': '5912312.00',
  'symbol': 'BHARTIARTL',
  'token': 10604,
  'ltp': 711.5},
 {'time': datetime.date(2022, 5, 6),
  'into': '6201.00',
  'inth': '6205.05',
  'intl': '5975.00',
  'intc': '6000.30',
  'ssboe': '1651795200',
  'intv': '3064865.00',
  'symbol': 'BAJFINANCE',
  'token': 317,
  'ltp': 6036.95},
 {'time': datetime.date(2022, 5, 6),
  'into': '13800.00',
  'inth': '13895.30',
  'intl': '13510.00',
  'intc': '13640.50',
  'ssboe': '1651795200',
  'intv': '351616.00',
  'symbol': 'BAJAJFINSV',
  'token': 16675,
  'ltp': 13783.85},
 {'time': datetime.date(2022, 5, 6),
  'into': '3488.30',
  'inth': '3555.00',
  'intl': '3460.00',
  'intc': '3499.75',
  'ssboe': '1651795200',
  'intv': '436366.00',
  'symbol': 'BAJAJ-AUTO',
  'token': 16669,
  'ltp': 3568.75},
 {'time': datetime.date(2022, 5, 6),
  'into': '690.00',
  'inth': '692.50',
  'intl': '668.10',
  'intc': '673.40',
  'ssboe': '1651795200',
  'intv': '15511195.00',
  'symbol': 'AXISBANK',
  'token': 5900,
  'ltp': 663.7},
 {'time': datetime.date(2022, 5, 6),
  'into': '3020.00',
  'inth': '3052.40',
  'intl': '3003.90',
  'intc': '3016.25',
  'ssboe': '1651795200',
  'intv': '923941.00',
  'symbol': 'ASIANPAINT',
  'token': 236,
  'ltp': 3005.25},
 {'time': datetime.date(2022, 5, 6),
  'into': '3898.65',
  'inth': '3898.65',
  'intl': '3791.05',
  'intc': '3827.35',
  'ssboe': '1651795200',
  'intv': '891448.00',
  'symbol': 'APOLLOHOSP',
  'token': 157,
  'ltp': 3766.35},
 {'time': datetime.date(2022, 5, 6),
  'into': '797.90',
  'inth': '820.95',
  'intl': '790.20',
  'intc': '811.40',
  'ssboe': '1651795200',
  'intv': '6150326.00',
  'symbol': 'ADANIPORTS',
  'token': 15083,
  'ltp': 792.6}]

In [20]:
finaldf = pd.DataFrame(symbolList)
finaldf['pct'] = finaldf.apply(lambda row: 100*( row.ltp - float(row.intc))/float(row.intc),axis=  1)
finaldf.sort_values(by = 'pct', inplace =True)
finaldf

,time,into,inth,intl,intc,ssboe,intv,symbol,token,ltp,pct
13,2022-05-06,2612.20,2659.00,2593.55,2620.65,1651795200,9068448.00,RELIANCE,2885,2518.30,-3.905520
17,2022-05-06,17499.80,17599.70,16975.00,16995.45,1651795200,89997.00,NESTLEIND,17963,16504.35,-2.889597
25,2022-05-06,919.00,934.30,902.50,915.40,1651795200,3713381.00,INDUSINDBK,5258,889.70,-2.807516
29,2022-05-06,2410.00,2599.00,2407.25,2563.35,1651795200,2491483.00,HEROMOTOCO,1348,2492.75,-2.754208
6,2022-05-06,1268.00,1290.00,1243.00,1283.70,1651795200,6925676.00,TATASTEEL,3499,1252.25,-2.449949
38,2022-05-06,184.50,188.95,183.05,187.40,1651795200,14257553.00,COALINDIA,20374,183.05,-2.321238
49,2022-05-06,797.90,820.95,790.20,811.40,1651795200,6150326.00,ADANIPORTS,15083,792.60,-2.316983
4,2022-05-06,1239.70,1299.00,1228.70,1290.75,1651795200,5745203.00,TECHM,13538,1261.15,-2.293240
22,2022-05-06,695.40,700.90,680.65,690.40,1651795200,3930624.00,JSWSTEEL,11723,678.35,-1.745365
40,2022-05-06,3245.00,3323.85,3187.10,3307.80,1651795200,560373.00,BRITANNIA,547,3252.05,-1.685410
11,2022-05-06,471.00,486.10,471.00,483.95,1651795200,16710020.00,SBIN,3045,475.90,-1.663395
48,2022-05-06,3898.65,3898.65,3791.05,3827.35,1651795200,891448.00,APOLLOHOSP,157,3766.35,-1.593792
27,2022-05-06,2125.00,2170.00,2106.20,2149.20,1651795200,1585602.00,HINDUNILVR,1394,2116.65,-1.514517
46,2022-05-06,690.00,692.50,668.10,673.40,1651795200,15511195.00,AXISBANK,5900,663.70,-1.440451
23,2022-05-06,259.00,267.35,258.90,266.65,1651795200,34490123.00,ITC,1660,262.95,-1.387587
15,2022-05-06,163.90,167.40,161.10,166.95,1651795200,16768573.00,ONGC,2475,164.75,-1.317760
26,2022-05-06,716.25,723.00,710.30,719.25,1651795200,12455025.00,ICICIBANK,4963,710.35,-1.237400
1,2022-05-06,815.00,815.00,779.45,786.85,1651795200,3256336.00,UPL,11287,777.60,-1.175573
3,2022-05-06,2240.00,2240.00,2195.45,2208.75,1651795200,1465638.00,TITAN,3506,2183.20,-1.156763
7,2022-05-06,418.85,420.20,407.00,408.55,1651795200,25142225.00,TATAMOTORS,3456,403.95,-1.125933
41,2022-05-06,357.00,359.80,353.00,357.30,1651795200,2348871.00,BPCL,526,353.40,-1.091520
34,2022-05-06,1590.40,1604.40,1551.05,1565.60,1651795200,525582.00,GRASIM,1232,1551.75,-0.884645
8,2022-05-06,770.00,778.50,762.95,764.95,1651795200,2003395.00,TATACONSUM,3432,758.25,-0.875874
35,2022-05-06,2410.00,2418.20,2351.35,2362.45,1651795200,407390.00,EICHERMOT,910,2344.30,-0.768270
36,2022-05-06,3929.80,3948.85,3880.00,3930.65,1651795200,239479.00,DRREDDY,881,3905.80,-0.632211
21,2022-05-06,1755.15,1794.95,1750.00,1775.30,1651795200,2847483.00,KOTAKBANK,1922,1767.50,-0.439362
0,2022-05-06,490.00,490.90,481.00,485.10,1651795200,9220891.00,WIPRO,3787,483.15,-0.401979
20,2022-05-06,1616.00,1633.00,1612.10,1622.45,1651795200,1439520.00,LT,11483,1616.15,-0.388302
30,2022-05-06,555.00,573.75,555.00,565.95,1651795200,3969111.00,HDFCLIFE,467,563.85,-0.371058
47,2022-05-06,3020.00,3052.40,3003.90,3016.25,1651795200,923941.00,ASIANPAINT,236,3005.25,-0.364691
16,2022-05-06,156.45,160.35,156.05,159.00,1651795200,22604305.00,NTPC,11630,159.00,0.000000
28,2022-05-06,450.00,454.25,439.00,443.75,1651795200,8595262.00,HINDALCO,1363,444.10,0.078873
19,2022-05-06,890.00,914.80,887.30,893.85,1651795200,4247088.00,M&M,2031,895.30,0.162220
31,2022-05-06,1330.00,1335.00,1313.00,1317.60,1651795200,13365634.00,HDFCBANK,1333,1319.85,0.170765
42,2022-05-06,711.25,723.90,707.75,710.25,1651795200,5912312.00,BHARTIARTL,10604,711.50,0.175994
9,2022-05-06,862.00,885.70,861.50,883.30,1651795200,2350532.00,SUNPHARMA,3351,885.40,0.237745
10,2022-05-06,24850.00,25059.20,23850.00,23973.65,1651795200,43939.00,SHREECEM,3103,24058.30,0.353096
5,2022-05-06,3459.00,3474.50,3424.50,3432.60,1651795200,2010812.00,TCS,11536,3445.10,0.364155
39,2022-05-06,937.80,946.35,925.40,934.75,1651795200,1828238.00,CIPLA,694,938.30,0.379781
2,2022-05-06,6300.00,6300.00,6160.00,6200.20,1651795200,499910.00,ULTRACEMCO,11532,6224.60,0.393536
12,2022-05-06,1073.00,1081.00,1052.20,1059.15,1651795200,1350057.00,SBILIFE,21808,1064.45,0.500401
43,2022-05-06,6201.00,6205.05,5975.00,6000.30,1651795200,3064865.00,BAJFINANCE,317,6036.95,0.610803
32,2022-05-06,2170.00,2190.00,2142.75,2150.65,1651795200,3862931.00,HDFC,1330,2168.30,0.820682
44,2022-05-06,13800.00,13895.30,13510.00,13640.50,1651795200,351616.00,BAJAJFINSV,16675,13783.85,1.050915
18,2022-05-06,7314.00,7359.90,7156.65,7279.25,1651795200,650559.00,MARUTI,10999,7360.30,1.113439
37,2022-05-06,4275.00,4310.55,4121.50,4165.85,1651795200,684913.00,DIVISLAB,10940,4231.10,1.566307
24,2022-05-06,1550.00,1561.85,1535.05,1542.85,1651795200,6171472.00,INFY,1594,1570.35,1.782416
45,2022-05-06,3488.30,3555.00,3460.00,3499.75,1651795200,436366.00,BAJAJ-AUTO,16669,3568.75,1.971569
33,2022-05-06,1049.90,1056.65,1028.95,1050.20,1651795200,4075606.00,HCLTECH,7229,1076.10,2.466197
14,2022-05-06,231.45,239.15,231.45,238.40,1651795200,13286390.00,POWERGRID,14977,245.15,2.831376

In [ ]:
finaldf = pd.DataFrame(symbolList)
finaldf['pct'] = finaldf.apply(lambda row: 100*( row.ltp - float(row.intc))/float(row.intc),axis=  1)
finaldf.sort_values(by = 'pct', inplace =True)
finaldf

In [21]:
finaldf.head(5)

,time,into,inth,intl,intc,ssboe,intv,symbol,token,ltp,pct
13,2022-05-06,2612.20,2659.00,2593.55,2620.65,1651795200,9068448.00,RELIANCE,2885,2518.30,-3.905520
17,2022-05-06,17499.80,17599.70,16975.00,16995.45,1651795200,89997.00,NESTLEIND,17963,16504.35,-2.889597
25,2022-05-06,919.00,934.30,902.50,915.40,1651795200,3713381.00,INDUSINDBK,5258,889.70,-2.807516
29,2022-05-06,2410.00,2599.00,2407.25,2563.35,1651795200,2491483.00,HEROMOTOCO,1348,2492.75,-2.754208
6,2022-05-06,1268.00,1290.00,1243.00,1283.70,1651795200,6925676.00,TATASTEEL,3499,1252.25,-2.449949

In [22]:
finaldf.tail(5)

,time,into,inth,intl,intc,ssboe,intv,symbol,token,ltp,pct
37,2022-05-06,4275.00,4310.55,4121.50,4165.85,1651795200,684913.00,DIVISLAB,10940,4231.10,1.566307
24,2022-05-06,1550.00,1561.85,1535.05,1542.85,1651795200,6171472.00,INFY,1594,1570.35,1.782416
45,2022-05-06,3488.30,3555.00,3460.00,3499.75,1651795200,436366.00,BAJAJ-AUTO,16669,3568.75,1.971569
33,2022-05-06,1049.90,1056.65,1028.95,1050.20,1651795200,4075606.00,HCLTECH,7229,1076.10,2.466197
14,2022-05-06,231.45,239.15,231.45,238.40,1651795200,13286390.00,POWERGRID,14977,245.15,2.831376